//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCUniversityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string descripcion { get; set; }
    }
}
